contract_address: 0x4Dc92C709aD77c3E9Af323C14d93578059208c12
private_key_path: keystore.json
private_key_passphrase: dustin@09876@nukleus
node_address: https://testnet.infura.io/g8VYSZ6DGzZv9iAi4xnp
max_gas_limit: 4150000
recipients_csv_path: airdrop-wallets.csv
batch_size: 120
